package gui;

import javafx.fxml.FXML;
import domein.DomainController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class GamesScreenController extends BaseScreenController {
	protected GamesScreenController(DomainController domainController, String resource) {
		super(domainController, resource);
	}

	@FXML
	private Label lblChooseGame;
	@FXML
	private ListView lstGames;

	// Event Listener on ComboBox[#comboBoxLanguage].onAction
	@FXML
	public void languageChoiceChanged(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ListView[#lstGames].onMouseClicked
	@FXML
	public void lstGamesChooseGame(MouseEvent event) {
		// TODO Autogenerated
	}
}
